conditions = {
    "Hypertension (high blood pressure)": False,
    "Asthma": False,
    "Arthritis": False,
    "Migraines": False,
    "Osteoporosis": False,
    "Chronic obstructive pulmonary disease (COPD)": False,
    "Depression": False,
    "Anxiety disorders": False,
    "Gastroesophageal reflux disease (GERD)": False,
    "Cardiovascular disease": False,
    "Diabetes": False,
    "High cholesterol": False,
    "Obesity": False,
    "Thyroid disorders": False,
    "Cancer": False,
    "Autoimmune disorders": False,
    "Alzheimer's disease": False,
    "Parkinson's disease": False,
    "Epilepsy": False,
    "Sleep apnea": False,
    "Kidney disease": False,
    "Liver disease": False
}
